ebooklib/epub.py

I read in an epub that was missing an title and then immediately tried to save it and got:
Traceback (most recent call last):
File "experiment.py", line 11, in <module>
epub.write_epub(output_filename, book, {})
File "C:\Users\clach04\py\ebooklib\ebooklib\epub.py", line 1220, in write_epub
epub.write()
File "C:\Users\clach04\py\ebooklib\ebooklib\epub.py", line 913, in write
self._write_opf_file()
File "C:\Users\clach04\py\ebooklib\ebooklib\epub.py", line 723, in _write_opf_file
'href': _href})
File "lxml.etree.pyx", line 3006, in lxml.etree.SubElement (src\lxml\lxml.etree.c:69555)
File "apihelpers.pxi", line 208, in lxml.etree._makeSubElement (src\lxml\lxml.etree.c:15876)
File "apihelpers.pxi", line 203, in lxml.etree._makeSubElement (src\lxml\lxml.etree.c:15811)
File "apihelpers.pxi", …

Set blank title if it is None

---

ebooklib/epub.py

ebooklib creates a fresh dcterms:modified meta element. Therefore if the lib is loading an existing epub with its own dcterms:modified element then for the sake of epub3 conformance we must omit the original one in favour of the new element.

Ensure only new modified date is included

---

ebooklib/epub.py

It's not necessarily the case that an epub's nav file is in the root dir; currently ebooklib makes that assumption. An item's file_name attribute is relative to the root dir. Therefore it's necessary to ensure the links in the nav file are relative to the nav file's current path.

Use relative paths in toc nav

---

ebooklib/epub.py

Hi @aerkalov 
Please, take a look at this pr. 
DOCTYPE was missed in the nav.xhtml file, this pr should fix it. 
Check attached image, it shows the difference:

Missed doctype in the nav.xhtml file

---

ebooklib/plugins/tidyhtml.py

http://tidy.sourceforge.net/docs/quickref.html#char-encoding
should --char-encoding utf8 instead of --utf8 (invalid option)

Enable utf8 in TidyPlugin

---

ebooklib/epub.py

in meta tag name should appear earlier than content attribute
from calibre ebook-edit check
>Some ebook readers such as the Nook fail to recognize covers if the content attribute comes before the name attribute. For maximum compatibility move the name attribute before the content attribute.

Attribute ordering of meta tag

---

ebooklib/epub.py

`<body>` is only 6 characters long, but `tree_str[7:n]` cuts off 7 :slightly_smiling_face:.
Thanks for this project, by the way! I'm finding it pretty handy.

Don't cut off first character of body in EpubHtml.get_body_content()

---

samples/04_markdown_parse/epub2markdown.py

Hi Alex,
This is a bug fix in **samples** for Python 3 support:
- use `print()` function (instead of `print` statement),
- use `with` statement to write the output files.
- use `format()` function (instead of `%` operator).
- organize imports.

Make `samples/04_markdown_parse` Python 2+3 compatible

---

ebooklib/epub.py

Epub accessibility checkers require that all epub:type rules which have corresponding ARIA roles use both. The ebooklib serializer for the nav element doesn't provide any entry point to manually add the `doc-toc` role. This change programmatically adds `role="doc-type"` to the nav at the same point at which `epub:type="toc"` is added.
References:
* [The EPUB-specific rules at the DAISY Ace epub accessibility checker](https://daisy.github.io/ace/rules/epub/)
* [doc-toc role in the Digital publishing WAI-ARIA module 1.0](https://www.w3.org/TR/dpub-aria-1.0/#doc-toc)
* [The DAISY knowledge base on using ARIA in epub](http://kb.daisy.org/publishing/docs/script/aria.html)

Add WAI-ARIA role to the nav element for accessibility.

---

ebooklib/epub.py

RTL books must have `dir` attribute both in body and HTML tags.

add direction for HTML tags

---

ebooklib/epub.py

`self._id_image` was used for defining static item id's when `self._id_static` should have been used. This PR addresses that problem

Issue #218 - Use correct variable for static item ids

---

ebooklib/epub.py

The XML declaration normally uses double quotes instead of single
quotes, and all the other containers use double quotes for the
declaration string. I want to update this in order to standardize the
declaration string quotes and because some xml parsers balk at single
quotes in the declaration.

Use double quotes for XML declaration in xml container

---

ebooklib/utils.py

The executing of `epub.read_epub` will fail with some Epub file. After some digging,I found it is caused by illegal characters in that ebook metadata file. 
Lucky,the current xml lib lxml used by `ebooklib` have an option to handle this situation [recover mode for XMLParser](https://lxml.de/api/lxml.etree.XMLParser-class.html).
I think a better compatibility XML parser is better for the project.

Using a more robust XML parser to improve the Epub compatibility

---

ebooklib/epub.py

For some EPUB ebook with cover, we want to set the TOC page title to
"Table of Contents" instead of the book title.
Usage of the changes:
```python
book = epub.EpubBook()
nav = epub.EpubNav(title="Table of Contents")
book.add_item(nav)
book.spine.append("nav")
epub.write_epub("toc.epub", book, {})
```

Add option to set custom title in toc page

---

ebooklib/epub.py

See https://github.com/aerkalov/ebooklib/issues/200.
According to [EPUB 3 spec](http://idpf.org/epub/30/spec/epub30-publications.html#ncx-superseded):
> EPUB 3 Reading Systems must ignore the NCX in favor of the EPUB Navigation Document

Ignore NCX if Navigation Document exists

---

docs/tutorial.rst

Fix typo of `Dublic Core` => `Dublin Core` in the documentation tutorial.

Fix dublin core typo in tutorial documentation

---

ebooklib/epub.py

RTL languages like Arabic needs to have consistent right to left direction. However, before this change, there's no ability to change TOC (nav) page  direction to RTL, even with book direction set to RTL.
```python
book = epub.EpubBook()
nav = epub.EpubNav(direction="rtl")
book.add_item(nav)
book.spine.append("nav")
epub.write_epub("toc.epub", book, {})
```
Nav HTML page will have `dir="rtl"`:
```html
</head>
<body dir="rtl">
<nav epub:type="toc" id="id" role="doc-toc">
```

Add an option to set toc page direction

---

ebooklib/epub.py

Fix the following warning when using ebooklib with the latest version of lxml (5.2.1):
> [ebooklib/epub.py:1423](https://github.com/aerkalov/ebooklib/blob/v0.18/ebooklib/epub.py#L1423): FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'

fix: lxml root warning

---

ebooklib/epub.py

Check for None rather than falsey-ness.
The current problem is that 
```python
book = epub.read_epub('test.epub', options={'ignore_ncx': False})
```
will raise a user warning because the current logic checks for Falsey-ness rather than None. The expected behaviour is that no warning should be raised as the option was passed explicitly (the warning about the default value doesn't matter). This pull request changes the deprecation check to check for None rather than falsey-ness.

Change deprecation check

---

ebooklib/epub.py

Using lxml's .text_content() instead of text because some ToC nodes look like this: 
```
<li>
<a href="text/chapter-1.xhtml"><span epub:type="z3998:roman">I</span>: Looking-Glass House</a>
</li>
```
This PR fixes that issue by using lxml's nested text extractor instead of using the root node's text alone.

Handle missing title from table of contents nodes that have children

---

docs/tutorial.rst
ebooklib/epub.py
setup.py

Hi :smile:, this PR resolves #271 
Usage of the changes:
```python
epub.write_epub('test.epub', book, {"compresslevel": 9})
```
Allowed values for compresslevel are 0 to 9 - see [ZipFile docs](https://docs.python.org/3/library/zipfile.html#zipfile-objects)
The default value is 6, it's also possible to use `None` with same effect

Add compresslevel

---

ebooklib/epub.py

I have encountered a couple epubs lately that have the condition where one of the `link_node` objects does not have a valid `href`. It's usually when the link node text is filled with whites spaces.
This is a simple and I believe save way to avert the issue.
The change simply checks that a `link_node` has a valid `href` before attempting to use it. This I think is inline with original intention to only process "valid" link nodes.

Bug fix. Prevent None join error when HREF is not found on a link_node.

---

ebooklib/epub.py

The method's documentation states that in python 3 it return bytes, but was previously returning strings in some situations.

Return bytes in EpubHtml's get_body_content

---

ebooklib/epub.py

When producing EPUBs from images, <svg> is employed to depict the appearance and layout of the images. At this point, it is utilized in conjunction with the `<meta name="viewport" content="" />` syntax.

An extension method for `<meta>` is added to the EpubHtml object
